version: '3.5'
services:
  slave1:
    container_name: eureka-consumer-01
    image: learn/eureka-consumer:1.0-SNAPSHOT
    networks:
      - learn-eureka-server-net
    ports:
      - 6761:6761
    environment:
      - SPRING_PROFILES_ACTIVE=slave1


networks:
  learn-eureka-server-net:
    name: learn-eureka-server-net
    driver: bridge