version: '3.5'
services:
  slave1:
    container_name: eureka-server-01
    image: learn/eureka-server:1.0-SNAPSHOT
    networks:
      - learn-eureka-server-net
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=slave1

  slave2:
    container_name: eureka-server-02
    image: learn/eureka-server:1.0-SNAPSHOT
    networks:
      - learn-eureka-server-net
    ports:
      - 8762:8762
    environment:
      - SPRING_PROFILES_ACTIVE=slave2

  slave3:
    container_name: eureka-server-03
    image: learn/eureka-server:1.0-SNAPSHOT
    networks:
      - learn-eureka-server-net
    ports:
      - 8763:8763
    environment:
      - SPRING_PROFILES_ACTIVE=slave3

networks:
  learn-eureka-server-net:
    name: learn-eureka-server-net
    driver: bridge